### ISSUE TITLE
Deleting the profile photo does not remove the photo from the user's profile

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#1]
Deleting the profile photo does not immediately remove the photo from the user's profile.

https://user-images.githubusercontent.com/58783823/139786920-f6729546-1fd9-4895-9742-652bc488a547.mov

**Comment by rakibansary** [comment]
We currently do not have a way in the Api to delete a members photo. The delete Api will need to delete the photo from the following places

1. Member Api (so member api response doesn't return a photoURL)
2. traits
3. onboarding_checklist (profile_photo)

For now, let's show the "Delete Photo" button only if the photo hasn't bee persisted in database. If a user lands on Getting Started page of the wizard and the photoUrl in member Api response is null, let's show a Delete Photo button, but if a photo was previously uploaded we should no longer show "Delete Photo" button.

**Comment by coderhacker** [comment]
QA Comments: This is passed on dev environment please find attached the video.

https://user-images.githubusercontent.com/62358241/140031496-41648fa7-77d1-4168-ad86-598332f70447.mp4
