### ISSUE TITLE
Contact Info : Timezone

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#10]
The list of timezones used in the Onboarding app and the connect app must be the same as they read and write to the same trait. Also it will be good to have the time zone list sorted alphabetically like in connect.
ref: https://github.com/topcoder-platform/micro-frontends-onboarding-app/blob/develop/src/constants/timezones.json
<img width="1440" alt="Screenshot 2021-11-02 at 1 26 12 PM" src="https://user-images.githubusercontent.com/58783823/139807435-0e0046ed-9beb-4c6a-838e-44daf97e6a8d.png">

<img width="1440" alt="Screenshot 2021-11-02 at 1 25 56 PM" src="https://user-images.githubusercontent.com/58783823/139807410-89f79fb9-d9ff-43be-a8ba-1ae219ab4b3f.png">

**Comment by vikasrohit** [comment]
I agree. @rakibansary you can use component from https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/Formsy/TimezoneInput.jsx or copy its list for the time being, if integrating with react-components library causes any issue. https://github.com/appirio-tech/connect-app/blob/dev/package.json#L88 is the way we are using this component library in connect-app.

**Comment by SathyaJayabal** [comment]
@rakibansary , the timezones are still not sorted alphabetically. I dont thing the fix is merged/deployed yet

<img width="1440" alt="Screenshot 2021-11-03 at 8 34 44 PM" src="https://user-images.githubusercontent.com/58783823/140086840-701fe8f5-3efb-48a9-8927-45c074fa6914.png">

**Comment by rakibansary** [comment]
Hey @SathyaJayabal, this has now been deployed.

**Comment by SathyaJayabal** [comment]
@rakibansary , the list is fixed. when a user clicks on the dropdown, the current selection must be highlighted.
<img width="1440" alt="Screenshot 2021-11-04 at 8 57 31 AM" src="https://user-images.githubusercontent.com/58783823/140253099-c0f9a7b0-0438-4b2b-8b8c-ef91a20ba616.png">

**Comment by rakibansary** [comment]
Ready for QA

![image](https://user-images.githubusercontent.com/1445965/140296387-5ddce980-d535-4c52-9cb1-0706a6b4d7c1.png)
