### ISSUE TITLE
Payment Setup: UI Issues

### ISSUE THREAD

**Issue by rakibansary** [topcoder-platform/micro-frontends-onboarding-app#101]
1. Add missing full name in Payment Setup page. Should be added to the sub pages as well - tax form & payment service

![image](https://user-images.githubusercontent.com/1445965/141037006-cc1b3217-0caa-47ca-9d90-5e32ef8bffe3.png)

2. "Topcoder Payment Policies" is a link. Style it like other links in the form (See "Please complete form W-9" in https://platform.topcoder-dev.com/onboard/payment-setup/tax-form/w-9/confirm) for example

![image](https://user-images.githubusercontent.com/1445965/141037139-8873d68d-2dfa-4430-8129-2ea9f4b65718.png)

3. The text support@topcoder.com in "Yes, I have emailed my details to support@topcoder.com" is a link, but not clickable. If you click on it, the checkbox is toggled. https://platform.topcoder-dev.com/onboard/payment-setup/payment-provider/paypal support@topcoder.com should behave like regular `mailto` links

4. Remove the text "Almost done, Be sure to setup..."

![image](https://user-images.githubusercontent.com/1445965/141037985-7d25be0f-f67b-4e66-93d3-ea94c90749b6.png)

Check [this](https://www.figma.com/file/V7oCzoOm36jncgiaa53frY/Member-Onboarding-MVP-UI?node-id=664%3A17274) for reference.

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/107

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

![image](https://user-images.githubusercontent.com/55895538/141093034-b79bba13-f3ec-40fe-9705-90ab6ad782bf.png)

![image](https://user-images.githubusercontent.com/55895538/141093185-449941cc-e5c8-4829-b8eb-e731ad844b58.png)

![image](https://user-images.githubusercontent.com/55895538/141093458-ade4ab9f-7b11-4674-ac90-43c44125b891.png)

![image](https://user-images.githubusercontent.com/55895538/141093831-49792425-4457-4476-95a6-c8d9c24dfa01.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env . Working as expected.
