### ISSUE TITLE
Open the respective Form on clicking Complete Form button.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#104]
Description:

At present when user clicks the "Complete Form W-8BEN/Complete Form w-9" button it is directing to the next page but in the next page we are asking "DID YOU COMPLETE YOUR DOCUSIGN TAX FORM?" without actually providing the W-9/W-8BEN Form to the user. It would be good if we can handle this in some way.

![image](https://user-images.githubusercontent.com/55895538/141057139-40694953-c219-4a31-b164-c4dd657d1e10.png)
![image](https://user-images.githubusercontent.com/55895538/141057225-0e893de3-aac5-4e8f-8738-a18264de99b9.png)

**Comment by rakibansary** [comment]
For now, let's do the following

1. When user clicks "Complete Form X"
2. Open the appropriate link in a new tab
3. Move to the next page

The expectation for now is, user will manually fill up the form and submit. They'll then come back to the onboarding wizard and confirm that they've submitted the paperwork.

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/115

**Comment by drasticdpk** [comment]
Verified on Dev as suggested above flow.

Reference
![image](https://user-images.githubusercontent.com/25297859/141142339-ad8bc25a-85b3-4e48-976e-b9e70ed0bcbf.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. The form is opening on clicking the Complete Form button
