### ISSUE TITLE
Minor UI issue in the Payment set-up screen and sub screens.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#105]
Description:

1. The payment serive Paypal and Western Union are mentioned as available in 200+ countries according to the design.

![image](https://user-images.githubusercontent.com/55895538/141069224-e5415612-fa5d-47a5-be39-91510255b77c.png)
![image](https://user-images.githubusercontent.com/55895538/141069309-753f7eb0-a5de-4726-a2ee-b20609b3a97a.png)

2. The Speed for the Western Union should be Up to 3 Business Days according to design.
![image](https://user-images.githubusercontent.com/55895538/141069663-6965acbb-f213-4ddb-aad1-8e8c3a316ba9.png)
![image](https://user-images.githubusercontent.com/55895538/141069798-1e958d79-81cb-4cf6-8be6-4a07c5e68444.png)

3. It would be nice to display the message "(your bank may charge additional fees)" after a space or in the next line as in design for better look.

![image](https://user-images.githubusercontent.com/55895538/141070024-f4d09ed1-099b-4b10-8666-e861d58654c0.png)
![image](https://user-images.githubusercontent.com/55895538/141070107-d6815c37-0874-4f3d-aeb5-3836d00595f6.png)

4. Typo error in the Paypal payment service screen. It should be "Please DO NOT **provide** a link to your PayPal account. We only need your PayPal email address." instead of **provider**

![image](https://user-images.githubusercontent.com/55895538/141072037-91492da1-081f-40c5-9204-a762896d962a.png)

5. Some letter is getting displayed in-between the text in Payment setup page.

![image](https://user-images.githubusercontent.com/55895538/141073590-e312b2b0-0ceb-434d-a5b6-765f3d3721d8.png)

6. All the confirmation text in Payment set-up page are in capital letter in the design.

![image](https://user-images.githubusercontent.com/55895538/141073691-5f334aa9-9aeb-4871-bb44-1d8b91a7dd5d.png)
![image](https://user-images.githubusercontent.com/55895538/141073732-4a2b70a1-1209-451d-b243-5069a95aa045.png)

7. It would be nice to display the text in two lines (as in design) instead of displaying as one line .

![image](https://user-images.githubusercontent.com/55895538/141075268-2dc69838-7f47-4a8f-a53d-c2758e1ddcbf.png)
![image](https://user-images.githubusercontent.com/55895538/141076193-59add609-be8b-4c2e-a55a-7ab1acbc5e00.png)

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/109

**Comment by drasticdpk** [comment]
Verified on dev mode.

**Comment by sandhiyakavi** [comment]
Issue no:6 All the confirmation text in Payment set-up page are in capital letter in the design is not yet resolved.

![image](https://user-images.githubusercontent.com/55895538/141258854-42b7ee5e-7e4b-4fd8-8d7f-9869a7799402.png)

**Comment by nursoltan-s** [comment]
<img width="1440" alt="Screen Shot 2021-11-11 at 16 48 54" src="https://user-images.githubusercontent.com/7783676/141267141-2759e7e9-6f51-412f-9c02-99cd0dd84942.png">

https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/139

**Comment by rakibansary** [comment]
@nursoltan-s 
![image](https://user-images.githubusercontent.com/1445965/141277773-678ac387-c50d-4888-8ff2-da28326b19a6.png)

Let's make the text expand when there's space.

**Comment by sandhiyakavi** [comment]
Verified on Prod Env

![image](https://user-images.githubusercontent.com/55895538/141421131-e0a73816-fb8e-4f84-82e1-09ff4c5b68a8.png)
