### ISSUE TITLE
Page continuously loading on clicking the Continue to Payment setup button

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#108]
Description:

Page continuously loading on clicking the Continue to Payment setup button.

Steps:
1. Sign up with new account.
2. Without entering any datas proceed to Step 3 by clicking the Continue to Payment setup button

![image](https://user-images.githubusercontent.com/55895538/141086050-31346880-1125-4ca1-8fe9-81658ff5ad56.png)

**Comment by drasticdpk** [comment]
Verified.

![image](https://user-images.githubusercontent.com/25297859/141148755-c31d9a5f-1951-41a4-8296-9aef25f7a103.png)

**Comment by lakshmiathreya** [comment]
Continue to Payment Setup working fine in Prod...
