### ISSUE TITLE
Work Experience details not getting saved.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#137]
Description:

Work Experience details not getting saved. 

![image (14)](https://user-images.githubusercontent.com/55895538/141247666-26abb3ca-34f1-4e80-a033-3329df133cc1.png)

**Comment by lakshmiathreya** [comment]
It seems to be working now :
<img width="1680" alt="Screenshot 2021-11-11 at 9 20 11 PM" src="https://user-images.githubusercontent.com/51733042/141327853-aa5ed3d6-665a-450f-adf1-a1e2b9501bc8.png">

**Comment by lakshmiathreya** [comment]
@sandhiyakavi pls reverify and update the latest findings here ...

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Able to save the Work Experience now without any issues

![image](https://user-images.githubusercontent.com/55895538/141422762-c2c75ae8-b905-482b-a529-0edfc8eb22ce.png)
![image](https://user-images.githubusercontent.com/55895538/141422894-984504a2-cd5b-47a8-97d0-16629ba885f4.png)
