### ISSUE TITLE
Minor UI issue in Payment set-up

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#138]
Description:

There should be some gap between the Title and the user's name| Handle shown in the Payment service completion page.

<img width="952" alt="close_payservice" src="https://user-images.githubusercontent.com/55895538/141247998-6bc2dfb7-58d9-43bf-bb14-3f830ea56e0f.png">
<img width="483" alt="close_paydesign" src="https://user-images.githubusercontent.com/55895538/141248010-40c1a2fd-a11f-464c-8705-0f0e3460d64d.png">

**Comment by nursoltan-s** [comment]
<img width="1440" alt="Screen Shot 2021-11-11 at 16 47 08" src="https://user-images.githubusercontent.com/7783676/141266888-e70d9f6a-a015-4964-bdd7-6ae52372f0bb.png">

https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/139

**Comment by rakibansary** [comment]
Thanks @nursoltan-s. That fixed the issue. Could you please also check this out.

The padding(top, left & right) of the steps (Getting Started, contact Info) and that of the payment/tax setup forms aren't the same

![image](https://user-images.githubusercontent.com/1445965/141268476-65ac39a8-8bcf-485b-90ba-112f79082dee.png)


vs 

![image](https://user-images.githubusercontent.com/1445965/141268596-46590f7c-7ba0-444a-bb68-37abcf419c4e.png)


Both forms needs proper padding. Figma reference: https://www.figma.com/file/V7oCzoOm36jncgiaa53frY/Member-Onboarding-MVP-UI?node-id=564%3A13517

**Comment by coderhacker** [comment]
This is fixed of Production:
![image](https://user-images.githubusercontent.com/62358241/141311328-8667b521-557c-4544-9a8b-81f32dfadb68.png)

CC @lakshmiathreya
