### ISSUE TITLE
Ensure all links to Register/Signup hit the Onboarding Wizard 

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/micro-frontends-onboarding-app#146]
https://topcoder.slack.com/archives/C02EB6JKG5N/p1636684095428400

cc @Oanh-and-only-Oanh @sandhiyakavi @SathyaJayabal @rakibansary @sushilshinde @drasticdpk

**Comment by rakibansary** [comment]
Current Status

<google-sheets-html-origin><style type="text/css"></style>

Link | Status | Managed By | Note
-- | -- | -- | --
https://topcoder.com/user-selection | Updated | quesks |  
https://topcoder.com/challenges | Updated | Community App Codebase | Signup Button in Navbar
https://topcoder.com/community | In Progress | Kirill | Contentful Driven
http://discussions.topcoder.com/ | Updated | quesks | Signup links to user-selection page
https://tco20.topcoder.com/ | In Progress | Community App Codebase/Ansary | Previous TCO Pages
https://www.topcoder.com/challenges/8cd464cd-f113-4b0b-b0aa-9ff2a4b95b86 | In Progress | Community App Code Base/Ansary | Register Button in Challenge Details page
https://platform.topcoder.com | ? | ? | Login button, switch to Signup. When user clicks Login, whether they'll log in or signup is not known & thus an appropriate retUrl can't be set. Requires updates in Auth0
https://platform.topcoder.com/earn/find/challenges/95b2d5a9-5d72-4321-a0e2-71cc851e0c48 | ? | ? | Register button in Challenge Details page
https://www.topcoder.com/gigs/16328384519390013350hzK | ? | ? | Modal that is shown after clicking "Apply to this Job"
https://challenges.topcoder.com | ? | ? | Possibly requires updating Auth0 rules(?) to go to https://platform.topcoder.com/onboard when mode=signUp 
https://connect.topcoder.com | Not Required | N/A | Business user does not require onboarding

**Comment by lakshmiathreya** [comment]
@SathyaJayabal had reported this - Users can signup from the Challenge Details page as well https://www.topcoder.com/challenges/8cd464cd-f113-4b0b-b0aa-9ff2a4b95b86 - @rakibansary pls add this to your table above

**Comment by Oanh-and-only-Oanh** [comment]
@lakshmiathreya, @sandhiyakavi @rakibansary, we also need to include all sign up from the platform MFEs.

**Comment by lakshmiathreya** [comment]
one more by @SathyaJayabal https://www.topcoder.com/community/learn

**Comment by Oanh-and-only-Oanh** [comment]
also, 
1. challenge details page on the EARNs MFE
2. there's a model window with the Register button when user is not logged in and visiting a gigs details page. This is both on Community App and EARN MFE.
![image](https://user-images.githubusercontent.com/47536078/141404698-a1e09f52-b8a4-45f7-be5b-b49e7234848f.png)

**Comment by sdgun** [comment]
http://challenges.topcoder.com/
https://connect.topcoder.com/

**Comment by sandhiyakavi** [comment]
Created Excel sheet for adding all the Signup routes: https://docs.google.com/spreadsheets/d/1TIDLE1J-K8wRFYAzIGsCIEYgtqJZDZ2rg7ClTOw4gec/edit#gid=0

Please add all your findings in the above excel sheet. It would be easier to track and reduce duplication if all the links are added to the Excel.

**Comment by rakibansary** [comment]
If you click on I'm the Talent on this page https://www.topcoder.com/user-selection, you'll be taken to topcoder.com/home. If you aren't logged in you see the Auth0 control, but ideally if you click on I'm the Talent you should be taken to https://accounts-auth0.topcoder.com/?retUrl=https://www.topcoder.com/home&mode=signUp with "Signup Tab" pre-selected.

**Comment by lakshmiathreya** [comment]
> If you click on I'm the Talent on this page https://www.topcoder.com/user-selection, you'll be taken to topcoder.com/home. If you aren't logged in you see the Auth0 control, but ideally if you click on I'm the Talent you should be taken to https://accounts-auth0.topcoder.com/?retUrl=https://www.topcoder.com/home&mode=signUp with "Signup Tab" pre-selected.

Let's track this for fix post TCO. Currently we will need to go with the workaround of having the user switch to Signup on the Auth0 control manually.

**Comment by lakshmiathreya** [comment]
Please find test results here https://docs.google.com/spreadsheets/d/1TIDLE1J-K8wRFYAzIGsCIEYgtqJZDZ2rg7ClTOw4gec/edit#gid=1158290694

**Comment by Oanh-and-only-Oanh** [comment]
this is great news. can we close this ticket yet?
