### ISSUE TITLE
Not able to remove all the Primary Interests 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#148]
When a user removes all the primary interests in step 1, the PUT operation is not called, as there are no primary interests selected. Hence the removed primary interests are not saved.

https://user-images.githubusercontent.com/58783823/141421423-f022f993-a765-4ab3-a4ca-49360782dce1.mov

Note: user is able to remove primary interest as far as we have at least one interest selected

**Comment by nursoltan-s** [comment]
PR: https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/163

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.


https://user-images.githubusercontent.com/55895538/146503040-3fc6d5f7-62df-4e47-8cfe-af4b9a950f0c.mp4

**Comment by sdgun** [comment]
Verified in prod

https://user-images.githubusercontent.com/4592712/148730688-99e6b17f-719e-40c3-8955-1b238c722ccd.mp4
