### ISSUE TITLE
Update The Paypal and Western Union links

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#149]
Payment setup step
The Paypal and Western Union links needs to be replaced with what we have in the payment policy document.
https://www.topcoder.com/thrive/articles/Payment%20Methods
ref: https://topcoder.slack.com/archives/C02EB6JKG5N/p1636701138466100

**Comment by vikasrohit** [comment]
@rakibansary we need this one fixed.

**Comment by rakibansary** [comment]
Links updated in https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/151

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/141464827-688c0a73-6934-42a9-a176-ab1974f700b2.mov
