### ISSUE TITLE
Remove step 5 (completion page)

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-onboarding-app#154]
**Changes to make:**

- Remove step 5 from the onboarding wizard

- Update UX/UI (button language) on step 4 to reflect changes

- Button on step 4 routes user to /home

- Update status icon  

![image](https://user-images.githubusercontent.com/47536078/145488552-2543e78c-0845-4742-af8f-5d31f7fa588c.png)

**Figma**: https://www.figma.com/file/V7oCzoOm36jncgiaa53frY/Member-Onboarding-MVP-UI?node-id=3531%3A9116
Pages:
MVP HiFi - Desktop 10/9/21 Changes
MVP HiFi - Mobile 10/9/21 Changes

**Comment by rakibansary** [comment]
Launched https://topcoder.com/challenges/4484bcc3-9dfe-4634-8368-a8a4d7c88474

**Comment by sandhiyakavi** [comment]
Verified in dev Env.

![image](https://user-images.githubusercontent.com/55895538/145797904-dd978df0-71d7-443f-b394-30f58e358549.png)
![image](https://user-images.githubusercontent.com/55895538/145798307-c3cd6ccd-7cba-4aa0-a468-6384de567fb1.png)

**Comment by Oanh-and-only-Oanh** [comment]
verified in dev. Please proceed @rakibansary

**Comment by sdgun** [comment]
Verified in prod.


https://user-images.githubusercontent.com/4592712/148731376-a237658e-2040-4d0c-b77e-cb79b4dff1ad.mp4
