### ISSUE TITLE
Add “Do Later” button on step 3 (payments/taxes)

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-onboarding-app#155]
Add “Do Later” button on step 3 (payments/taxes)

**Figma**: https://www.figma.com/file/V7oCzoOm36jncgiaa53frY/Member-Onboarding-MVP-UI?node-id=3531%3A9116
**Pages**:
MVP HiFi - Desktop 10/9/21 Changes
MVP HiFi - Mobile 10/9/21 Changes

**Notes on Mobile:**

- “Back” buttons have changed to just the icon. Removing the “Back” text
- “Continue” buttons have changed to “Next” text
- This is to allow for the “skip” button on step 3
- Desktop button text remains the same as the current onboarding version

**Comment by rakibansary** [comment]
Launched https://topcoder.com/challenges/4484bcc3-9dfe-4634-8368-a8a4d7c88474

**Comment by sandhiyakavi** [comment]
@rakibansary  For Mobile related change, the "Back" and "Next" button are changed only in the Payment setup page. All other pages/subpages of payment setup are having the same previous buttons. (https://www.figma.com/file/V7oCzoOm36jncgiaa53frY/Member-Onboarding-MVP-UI?node-id=3532%3A13408)

![image](https://user-images.githubusercontent.com/55895538/145796462-ceb65325-5a60-4fa9-a972-38618c570a96.png)
![image](https://user-images.githubusercontent.com/55895538/145796523-b00b4698-7e77-4bb0-a591-31c2895fa200.png)

![image](https://user-images.githubusercontent.com/55895538/145796390-99c500d8-da32-468f-98dc-eb2cec59eeca.png)

Desktop changes are fine.

![image](https://user-images.githubusercontent.com/55895538/145792053-bc8132dc-a18c-4514-a8e4-0a235c2c860d.png)
![image](https://user-images.githubusercontent.com/55895538/145792338-6e9e581c-63a3-4d89-a05e-1168798c6553.png)

**Comment by Oanh-and-only-Oanh** [comment]
verified in dev. Please proceed @rakibansary

**Comment by sandhiyakavi** [comment]
@rakibansary In  Step 2 is "Continue to Payment setup" button is still not changed to "Next" . Other pages are fine.

![image](https://user-images.githubusercontent.com/55895538/146319046-bfdc47bc-8b6a-490f-9a65-24966250b2e9.png)

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. All pages in Desktop as well as Mobile are displaying correctly.

![image](https://user-images.githubusercontent.com/55895538/147034509-331dcc1f-dc60-4c64-9aec-9f27e83a4211.png)
