### ISSUE TITLE
Country field is not prefilled with the value entered during Signup

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#159]
Description:
Country field in Onboarding app is not prefilled with the value entered during Signup.

<img width="960" alt="signup" src="https://user-images.githubusercontent.com/55895538/145787842-c9ced909-1362-49ee-babd-b9cab0f35e6c.png">
<img width="960" alt="country_field" src="https://user-images.githubusercontent.com/55895538/145787864-1ef377ca-8afa-4f09-a44c-09d92f5ddaac.png">

But it's getting displayed in Community app now

![image](https://user-images.githubusercontent.com/55895538/145788041-604a7b98-7fa2-4dca-9e00-ce68f3f07bbf.png)

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

<img width="956" alt="signup_country" src="https://user-images.githubusercontent.com/55895538/146909011-ec1bfcea-4fcd-4e5f-9d58-272cde2e185d.png">
<img width="960" alt="onboard_country" src="https://user-images.githubusercontent.com/55895538/146909026-9585941d-c6c9-4d07-933b-1e340ce87d5d.png">
<img width="960" alt="country_settings" src="https://user-images.githubusercontent.com/55895538/146909028-1a698db9-4aff-4299-ad1e-cd117145f339.png">

**Comment by sdgun** [comment]
Verified in prod.

![image](https://user-images.githubusercontent.com/4592712/148730352-ef6f0a17-fee9-46a6-ad8a-46cdee89aae1.png)
