### ISSUE TITLE
Hide Payment Setup Step

### ISSUE THREAD

**Issue by rakibansary** [topcoder-platform/micro-frontends-onboarding-app#16]
We'll integrate payment setup after correctly implementing Tax Forms and Payment Service Provider steps. In our current implementation /onboard/payment-setup displays "Not Implemented" and we want to hide that step altogether.

1. Remove Payment Setup step
2. `Continue to Payment Setup` in Contact Details page should be replaced with `Continue to Build My Profile`
3. The step counter should reflect the removal of Payment setup - 4 steps instead of 5 total steps & the context menu should not have Payment Setup
4. In the final step of the Wizard - Onboarding Complete, under the next "Congratulations" add new paragraph saying "Almost done! Be sure to go set up your payment so you can get paid for your work", below it should be the text "Now it's time to..."

**Comment by SathyaJayabal** [comment]
@rakibansary, 
1. The step counter is incorrect in the steps 3 and 4
<img width="1440" alt="Screenshot 2021-11-03 at 10 25 25 AM" src="https://user-images.githubusercontent.com/58783823/140011731-d9fb8947-fca4-4df3-96de-ea82e8c335b3.png">

<img width="1440" alt="Screenshot 2021-11-03 at 10 26 08 AM" src="https://user-images.githubusercontent.com/58783823/140011743-65d754da-0a15-4e0d-b19a-299494612459.png">

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-11-03 at 8 29 12 PM" src="https://user-images.githubusercontent.com/58783823/140085392-0103f327-3ccb-401a-bbcf-fd5e576e0b04.png">
<img width="1440" alt="Screenshot 2021-11-03 at 8 29 22 PM" src="https://user-images.githubusercontent.com/58783823/140085424-e718adee-0ef8-496a-9cff-3d0ae669793b.png">
