### ISSUE TITLE
Mobile: Minor UI issue

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#160]
Description:

The tick symbol for the completion of payment service is small.

![image](https://user-images.githubusercontent.com/55895538/145959783-edca9e6f-1d61-4f57-abda-a25a771aa707.png)

Mobile model: Apple iphone 12 mini
version: 15.0
Browser: Safari

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

![image](https://user-images.githubusercontent.com/55895538/146318871-cd79dce7-e0e2-4293-bd00-1c0e7fd588fc.png)

**Comment by sdgun** [comment]
Verified in prod

![Screenshot_20220110-131457_Chrome](https://user-images.githubusercontent.com/4592712/148732505-a90015e6-0a6b-42fc-b3c0-8194c70613d9.jpg)
