### ISSUE TITLE
Not able to access the Work Manager app once the address details are saved.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#175]
Description:

Not able to access the Work Manager app once the address related fields are saved in Step 2 of Onboarding app due to v3 api issue.

Refer: https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/166#issuecomment-999546205

**Comment by rakibansary** [comment]
Onboarding app and community app sending createdAt, updatedAt from the client side was the cause of this issue. Member Api was coded to expect these values from the client side and should probably be cleaned up: https://github.com/topcoder-platform/member-api/blob/develop/src/services/MemberService.js#L216-L219

**Comment by SathyaJayabal** [comment]
verified on dev.  V# member api does not fail now after updating address details from v5 (onboarding flow or the settings page)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env.

![image](https://user-images.githubusercontent.com/55895538/148730031-0344e7fc-a59e-4654-a585-67ebfd510887.png)
