### ISSUE TITLE
Not able to remove Bio once entered.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#176]
Description:

Not able to remove the  Bio field in step 4 once entered.

https://user-images.githubusercontent.com/55895538/148176747-3d7d6b12-e482-4705-bfa1-a9647d219918.mp4

**Comment by rakibansary** [comment]
Member API has now been [updated](https://github.com/topcoder-platform/member-api/pull/71/commits/7eee41ddb1b8694e52540cc803f6ca3c039631ac) to allow empty "bio"

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/148222534-5d60df53-e6ab-4b2e-8d38-0ecce92a0f4d.mov

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/148731983-3adaece9-3d53-4590-a1f4-0e140220d904.png)
