### ISSUE TITLE
Able to access all the links in the navbar of the Onboarding app.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#178]
Description:

The user is now able to access all the links in the navbar of the Onboarding app.

![image](https://user-images.githubusercontent.com/55895538/148512796-92b2e2bc-6916-4866-a009-e68c9fc3c223.png)

**Comment by nursoltan-s** [comment]
PR: https://github.com/topcoder-platform/micro-frontends-navbar-app/pull/62

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. All the links are inaccessible now.

![image](https://user-images.githubusercontent.com/55895538/148722886-992d96cb-7a4c-4bba-a394-441043f83533.png)

**Comment by sdgun** [comment]
Verified in production env.

![image](https://user-images.githubusercontent.com/4592712/148729688-8576716d-d240-4cc1-a661-7bfcc0c903ce.png)
