### ISSUE TITLE
Build Your profile: Traits must not be created if the user has not entered data

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#19]
Traits must not be created if the user has not entered data. Traits are created with empty values even when user has not entered any data.

https://user-images.githubusercontent.com/58783823/139834315-a81859bb-e297-4c4c-a1c8-12c8ade71add.mov

**Comment by SathyaJayabal** [comment]
Note: Also note the duplicate get calls before each POST. One get call should be enough before POST calls.

**Comment by rakibansary** [comment]
> Note: Also note the duplicate get calls before each POST. One get call should be enough before POST calls.

This is now fixed in #44

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/57

**Comment by rakibansary** [comment]
Hi @nursoltan-s,

I've added comments in the pull request - https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/57#pullrequestreview-798121929. 

Thanks

**Comment by SathyaJayabal** [comment]
Verified on dev
Traits are not created when user does not enter nay data,  traits are created when user enters data for first time, traits are updated when user updates their traits info.

https://user-images.githubusercontent.com/58783823/140502450-964f6f84-4677-409a-96d9-4f7923a4d0b2.mov
