### ISSUE TITLE
Minor UI Issues

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#2]
1. The visual when user has not added their image yet is different from the design
<img width="1440" alt="Screenshot 2021-11-02 at 9 47 56 AM" src="https://user-images.githubusercontent.com/58783823/139786237-dff430e6-b6a2-4fec-971b-eca26676c461.png">

2. The step progress visual is different from the design
<img width="1440" alt="Screenshot 2021-11-02 at 9 49 33 AM" src="https://user-images.githubusercontent.com/58783823/139786337-1c5ed7f5-d375-4e48-acc2-7421e01bbb3e.png">

3. Delete / edit icons are slightly different in style and size from design
<img width="1440" alt="Screenshot 2021-11-02 at 9 58 52 AM" src="https://user-images.githubusercontent.com/58783823/139787071-9f7448fc-00cd-43ec-ba11-ece007452f16.png">

4. Typo in the "Add Anothet Skill" button, It should be "Add Another Skill"
<img width="1088" alt="Screenshot 2021-11-02 at 10 17 11 AM" src="https://user-images.githubusercontent.com/58783823/139788431-70a94623-f510-4f66-a99b-6fcc41a47eed.png">

**Comment by coderhacker** [comment]
QA Comment: This is passed on dev please find attached video:

https://user-images.githubusercontent.com/62358241/140031926-83d96275-6f31-4f6e-bcd1-1dc7fa5572cd.mp4

**Comment by SathyaJayabal** [comment]
@rakibansary , can we add this grey placeholder cirlce when profile picture is not uploaded.
<img width="1440" alt="Screenshot 2021-11-03 at 2 35 15 PM" src="https://user-images.githubusercontent.com/58783823/140033473-b8b5455c-b490-44f2-8a06-2c99519d856d.png">
<img width="730" alt="Screenshot 2021-11-03 at 2 35 35 PM" src="https://user-images.githubusercontent.com/58783823/140033494-f548f9e5-ed98-4724-8413-d9062ae69f21.png">

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1135" alt="Screenshot 2021-11-04 at 9 00 28 AM" src="https://user-images.githubusercontent.com/58783823/140253390-0ba4eed3-8041-439b-9890-7a5487a9742e.png">
