### ISSUE TITLE
Minor UI Issues 2

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#21]
1. Typo(extra `.`) in Your Title and Bio text.
<img width="665" alt="Screenshot 2021-11-02 at 4 51 05 PM" src="https://user-images.githubusercontent.com/58783823/139837635-d71b00cb-95eb-4ba6-bc69-b12a36c6c935.png">
Design for ref
<img width="520" alt="Screenshot 2021-11-02 at 4 54 37 PM" src="https://user-images.githubusercontent.com/58783823/139840252-6deccde3-4240-47b5-aff8-467b0f88219a.png">

2. Bio field must be larger
<img width="658" alt="Screenshot 2021-11-02 at 5 12 26 PM" src="https://user-images.githubusercontent.com/58783823/139840114-54b10468-4ee3-4370-a1b7-882b8f17aa99.png">
<img width="1330" alt="Screenshot 2021-11-02 at 5 12 17 PM" src="https://user-images.githubusercontent.com/58783823/139840120-f13a6b36-845c-410b-89ff-bbd319b88f7a.png">

3. The user entered text in text boxes is a bit cut off on the bottom
<img width="675" alt="Screenshot 2021-11-02 at 5 15 40 PM" src="https://user-images.githubusercontent.com/58783823/139840573-949170f3-6a77-4c89-a2e4-ee18b3054bbc.png">

4. The default text must follow a consistent sentence case style like in the design. 

<img width="689" alt="Screenshot 2021-11-02 at 5 26 42 PM" src="https://user-images.githubusercontent.com/58783823/139842131-3297b4fb-cca6-40b3-8118-ac4007761683.png">
<img width="716" alt="Screenshot 2021-11-02 at 5 27 30 PM" src="https://user-images.githubusercontent.com/58783823/139842139-baf48f47-4261-450c-8c41-f4808a0922ec.png">
design for reference:
<img width="239" alt="Screenshot 2021-11-02 at 5 30 06 PM" src="https://user-images.githubusercontent.com/58783823/139842237-3dcbf42a-4824-4d94-8bb5-fdce05d86f3b.png">

5. Typo in step 2: oppurtunities must be opportunities
<img width="1440" alt="Screenshot 2021-11-03 at 2 43 20 PM" src="https://user-images.githubusercontent.com/58783823/140034585-a8a371ff-ae36-4dbe-88db-992b660df7c9.png">

**Comment by lakshmiathreya** [comment]
All above UI Issues fixed: 
<img width="1680" alt="Screenshot 2021-11-04 at 9 22 12 AM" src="https://user-images.githubusercontent.com/51733042/140255277-32693d71-a018-4632-a0c8-2beb7aa5f93a.png">
<img width="1680" alt="Screenshot 2021-11-04 at 9 22 06 AM" src="https://user-images.githubusercontent.com/51733042/140255307-7aac88fe-a8bd-4f07-a2c1-4634662abc4c.png">

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2021-11-04 at 8 32 17 AM" src="https://user-images.githubusercontent.com/51733042/140255348-f46d64f7-e160-4ca5-a0f9-cc588f7ddf10.png">

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2021-11-04 at 8 32 49 AM" src="https://user-images.githubusercontent.com/51733042/140255381-76cf82be-a08e-49ee-85b3-ad7fdb93c0ae.png">

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2021-11-04 at 9 10 07 AM" src="https://user-images.githubusercontent.com/51733042/140255435-8f31aace-df7f-429d-b195-33e126f7489d.png">

**Comment by lakshmiathreya** [comment]
@SathyaJayabal pls mark this as Dev QA Pass
