### ISSUE TITLE
Address fields are not getting saved to v3

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#23]
1. Go to step 2 of the onboarding flow
https://platform.topcoder-dev.com/onboard/contact-details
2. Enter Address Line 1 and Address Line 2 values
3. Click on "Continue to  Payment Setup" button
4. Check the member profile settings page. The address values are not reflected here
https://www.topcoder-dev.com/settings/profile#basic-info

**Comment by SathyaJayabal** [comment]
@rakibansary , observed the following on the basic_info traits.

1. New user who has not edited their profile settings page:
`addresses` , `primaryInterestInTopcoder` , `description` values are saved to v3 and available in the settings page 
Only `country` field is not reflected in v3.

2. User who has edited their profile settings page:
`addresses` , `country` `description` values are not saved to v3 and not reflected in the settings page 
Only `primaryInterestInTopcoder` field is saved in v3 reflected in the settings page.

Other traits and skills are fine and get saved to v3.

**Comment by rakibansary** [comment]
Hi @SathyaJayabal,

This should be ready for QA. Sync from onboarding app to CA settings page works as expected, however I'm seeing CA fail when trying to save traits.

**Comment by SathyaJayabal** [comment]
@rakibansary , once the address filed are saved from the onbaording flow, user is not able to edit their profile settings page.
<img width="1440" alt="Screenshot 2021-11-04 at 4 43 05 PM" src="https://user-images.githubusercontent.com/58783823/140304155-aca6a657-4d97-49f7-8c51-f857779ca044.png">
error message
`Unable to unmarshall the string {\"traitId\":\"basic_info\",\"data\":[{\"country\":\"Angola\",\"primaryInterestInTopcoder\":\"\",\"addresses\":[{\"streetAddr1\":\"address OB\",\"streetAddr2\":\"address OB\",\"zip\":\"zip OB\",\"city\":\"city OB\",\"stateCode\":\"state OB\",\"type\":\"HOME\"}],\"description\":\"my bio\",\"title\":\"my title\"}]}into class com.appirio.service.member.api.MemberProfileTraitData`

**Comment by SathyaJayabal** [comment]
@rakibansary , this is fixed.

**Comment by SathyaJayabal** [comment]
Note: we did notice a sync issue when user later on edits their profile from the settings page. issue logged here
https://github.com/topcoder-platform/member-api/issues/65
cc @rakibansary @sushilshinde @vikasrohit

**Comment by lakshmiathreya** [comment]
This is not working as expected in Prod: 
1. An active user gets an inactive user error while Profile settings are being accessed. 
2. Title is not synced
3.  Company name is not synced

<img width="1680" alt="Screenshot 2021-11-11 at 9 55 35 PM" src="https://user-images.githubusercontent.com/51733042/141333153-378d2cef-dfe3-4f46-bca9-166b2a2d825e.png">

<img width="1680" alt="Screenshot 2021-11-11 at 9 55 48 PM" src="https://user-images.githubusercontent.com/51733042/141333138-bd2a2d88-5e6c-40d0-8145-fd6ac9f81ba3.png">

<img width="1680" alt="Screenshot 2021-11-11 at 9 55 52 PM" src="https://user-images.githubusercontent.com/51733042/141333119-75fe41ad-eec7-4575-8e47-92d4e41de4aa.png">

**Comment by SathyaJayabal** [comment]
Closing this as we are now using v3 member traits to save data from the onboarding flow
