### ISSUE TITLE
"Explore Topcoder Home" Link

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#24]
What should the "Explore Topcoder Home" link to.
http://topcoder-dev.com/home
or
Current implementation: 
https://platform.topcoder-dev.com/

<img width="1369" alt="Screenshot 2021-11-02 at 8 43 25 PM" src="https://user-images.githubusercontent.com/58783823/139875103-7bab6c54-6f98-44a0-b51f-89b414323127.png">

**Comment by Oanh-and-only-Oanh** [comment]
It should be linked to http://topcoder-dev.com/home

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-11-03 at 5 36 52 PM" src="https://user-images.githubusercontent.com/58783823/140057614-69f367b0-f8ad-4884-8f4f-3528f47d2284.png">

**Comment by Oanh-and-only-Oanh** [comment]
please confirm it works with clean browser/no cookies, user lands on onboarding and goes to /home after onboarding.

@SathyaJayabal, it's not wired up to SSO properly. clicking on the explore topcoder home button takes them to the sign in page. This shouldn't happen.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , it will work correctly in prod. In dev http://topcoder-dev.com/home is getting redirected to 
https://community-app.topcoder.com/home (prod) that is causing the login. 

@sushilshinde can you remove this redirection in dev

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. It is directing to https://www.topcoder.com/home and not getting redirected.


https://user-images.githubusercontent.com/55895538/141096176-3dabfe1c-db94-4a6e-ae26-4183504595b1.mp4
