### ISSUE TITLE
Update to using v5 APIs

### ISSUE THREAD

**Issue by rakibansary** [topcoder-platform/micro-frontends-onboarding-app#25]
Onboarding App is currently using both v3 and v5 Apis. We should be using v5 Apis everywhere. Specifically

# On Getting Started Page of the wizard
1. traits (GET /v3/members/:handle/traits) should be updated to use (GET /v5/members/:handle/traits)
2. users existing skills are fetched using GET /v3/members/:handle/skills. This should be updated to use GET /v5/members/:handle/skills
3. skills are saved using PATCH /v3/members/:handle/skills. This should be replaced with PATCH /v5/members/:handle/skills
4. Countres are fetched using GET /v3/members/lookup/countries - it's okay to keep this since v5 member Api doesn't have a country lookup

**Comment by SathyaJayabal** [comment]
verified here
https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/5#issuecomment-959116865
