### ISSUE TITLE
User should not be able to navigate away from the onboarding flow

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#27]
User should not be able to navigate away from the onboarding flow. The buttons menus etc must be disabled/hidden

**Comment by rakibansary** [comment]
Fixed in https://github.com/topcoder-platform/micro-frontends-navbar-app/pull/41

**Comment by SathyaJayabal** [comment]
@rakibansary , user can still navigate to the profile page from the user dd menu
 
<img width="306" alt="Screenshot 2021-11-03 at 4 25 12 PM" src="https://user-images.githubusercontent.com/58783823/140048232-abe51d2e-65a0-4e36-b8d7-58dbd82a108c.png">

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-11-03 at 7 11 24 PM" src="https://user-images.githubusercontent.com/58783823/140070880-645a1cab-4695-44c7-b76a-e297f1067d64.png">
