### ISSUE TITLE
Add Skills Clariifications

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#3]
1. When user clicks on the "Add Another Skill" button, which category must be selected in the skills popup.
 a. No category selected 
 b. The last Category that the user had viewed
<img width="1440" alt="Screenshot 2021-11-02 at 10 16 35 AM" src="https://user-images.githubusercontent.com/58783823/139789306-511eb113-bbc9-46c3-9b7b-2fa9cc654618.png">

2. In the skill popup, do we display the user's selected skills only under the respective categories ?
Current implementation shows the skills under all categories

https://user-images.githubusercontent.com/58783823/139788924-148bcf19-93f9-40c4-a97e-929095f048a0.mov

3. Top skills: we display a few skills by default under each category.
At present, we display the first 10 skills under each category from the json here
https://github.com/topcoder-platform/micro-frontends-onboarding-app/blob/develop/src/constants/skills.json
Do we need to identify, hardcode and use the top 10 skills for each category and across all categories(when no category is selected) ?
<img width="1440" alt="Screenshot 2021-11-02 at 10 32 39 AM" src="https://user-images.githubusercontent.com/58783823/139789428-0d85c1d2-aaeb-442f-9e3f-9c569da7891e.png">

4. When a user searches for a skill, do we show only the skills in the selected category ?
<img width="1440" alt="Screenshot 2021-11-02 at 10 40 43 AM" src="https://user-images.githubusercontent.com/58783823/139790007-9ad9e3ff-0993-463e-ad52-64d6ec7c6ca9.png">

**Comment by Oanh-and-only-Oanh** [comment]
@rakibansary
3. Top skills: we display a few skills by default under each category.
At present, we display the first 10 skills under each category from the json here
https://github.com/topcoder-platform/micro-frontends-onboarding-app/blob/develop/src/constants/skills.json
Do we need to identify, hardcode and use the top 10 skills for each category and across all categories(when no category is selected)? 

Yes, please identify and display the top 10 skills for each category across and across all categories when no category is selected.

**Comment by trevorgerring** [comment]
@rakibansary 
1. The last category the user selected
2. Just show the selected skills under their respective categories 
4. Yes, only show the skills in their selected category

**Comment by SathyaJayabal** [comment]
@rakibansary 
1. Already implemented
2. Needs to be fixed
3. Needs to be implemented
4. Already Implemented

**Comment by Oanh-and-only-Oanh** [comment]
@trevorgerring @rakibansary @SathyaJayabal,

We'd like to make the following UI changes (only if it doesn't jeopardize our timeline).

1) remove these 3 categories with "Add Skills" button
![image](https://user-images.githubusercontent.com/47536078/140209073-93e5adfd-48fb-493b-85e8-99241b4d15d4.png)

**Comment by trevorgerring** [comment]
@Oanh-and-only-Oanh What is the reasoning for this? Would the Add Skills modal still have the categories?

**Comment by SathyaJayabal** [comment]
https://topcoder.slack.com/archives/C02EB6JKG5N/p1635993511267800?thread_ts=1635980232.267200&cid=C02EB6JKG5N

**Comment by dashu-baba** [comment]
Fix given at https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/52

**Comment by rakibansary** [comment]
Top skills are determined by a rank property in the hardcoded list of [skills](https://github.com/topcoder-platform/micro-frontends-onboarding-app/blob/dev-without-payment-step/src/constants/skills-prod.json). The rankings were assigned randomly, but we'll need to manually go through all the skills and assign an appropriate rank. 

I assume later we'd use some sort of metrics to assign the ranks.

**Comment by rakibansary** [comment]
@SathyaJayabal this should be ready for QA. However still don't properly handle removing skills. This is being tracked in #48

**Comment by SathyaJayabal** [comment]
verified the following:

1. Skills dropdown sorted by rank and top 10 skills removed
<img width="1440" alt="Screenshot 2021-11-04 at 4 26 47 PM" src="https://user-images.githubusercontent.com/58783823/140302163-6db44f40-c82a-4e34-b39f-a3d5e5315204.png">

2. Selected skills shown only under respective category

https://user-images.githubusercontent.com/58783823/140302023-a8fa7c9d-82d2-4d79-9ac5-f8a5c3806d0d.mov

**Comment by SathyaJayabal** [comment]
@rakibansary, all issues fixed.

Only pending thing in this ticket:
https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/3#issuecomment-960246290

cc @Oanh-and-only-Oanh @trevorgerring

**Comment by Oanh-and-only-Oanh** [comment]
@rakibansary @SathyaJayabal,

 Regarding only pending thing in this ticket:
#3 (comment)
identify and show 10 top skills across all categories when no category is selected.

**Comment by SathyaJayabal** [comment]
verified on prod
