### ISSUE TITLE
Add Payment Setup step

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#32]
Add Payment Setup step

**Comment by sandhiyakavi** [comment]
The Payment confirmation text always shows Tax form W-9 and Payment service 'Payoneer' even if chose different Tax form/payment service.

![image](https://user-images.githubusercontent.com/55895538/141247273-492f6cec-0d02-46a7-896d-81d2ae943223.png)

**Comment by sandhiyakavi** [comment]
Tax form issue is resolved but Payment service if we choose Western Union it is still displaying Payoneer in the confirmation text.

**Comment by sandhiyakavi** [comment]
Verified in Prod env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/141280527-cefadb69-1fde-4aff-8539-a2836e9c6ee7.png)
