### ISSUE TITLE
Sort all drop downs alphabetically

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-onboarding-app#36]
sort all drop downs and selected item buttons throughout the wizard alphabetically

**Comment by rakibansary** [comment]
We have the following dropdowns

1. Getting Started: Skills -> Should be sorted by (rank descending, label). Tracked by #3 
2. Contact Details: Country Dropdown -> Needs fixing
3. Contact Details: Start Time, End Time -> Sort order is correct
4. Build Your Profile: Industry -> Needs Fixing
5. Build Your Profile: Language -> Needs Fixing
6. Build Your Profile: Spoken Level, Written Level -> Not sorted alphabetically, but makes sense to keep the current order [Basic, Intermediate, Advanced, Native]

@dashu-baba can you please take a look at this one.

**Comment by dashu-baba** [comment]
@rakibansary 
Confirming the order of skills
Skills -> Should be sorted by (rank ascending, label ascending)

**Comment by dashu-baba** [comment]
Fix given at https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/52

**Comment by SathyaJayabal** [comment]
Getting Started: Skills -> Should be sorted by (rank descending, label). Tracked by Add Skills Clariifications #3 - Fixed
Contact Details: Country Dropdown -> Fixed
<img width="1440" alt="Screenshot 2021-11-04 at 4 47 45 PM" src="https://user-images.githubusercontent.com/58783823/140304775-809e26ea-30fc-49c0-8a7b-bb9c37df15be.png">

Contact Details: Start Time, End Time -> Sort order is correct
Build Your Profile: Industry -> Fixed
<img width="1440" alt="Screenshot 2021-11-04 at 4 48 56 PM" src="https://user-images.githubusercontent.com/58783823/140304867-5d788ee2-c525-4ed1-acd6-67218f6be208.png">

Build Your Profile: Language -> Fixed
<img width="1440" alt="Screenshot 2021-11-04 at 4 49 22 PM" src="https://user-images.githubusercontent.com/58783823/140304919-1d15b618-8972-4286-b910-2c984eb2f129.png">

Build Your Profile: Spoken Level, Written Level -> Not sorted alphabetically, but makes sense to keep the current order [Basic, Intermediate, Advanced, Native]
