### ISSUE TITLE
Year date picker UI change

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-onboarding-app#37]
Change to date picker UI instead of calendar UI for easier usability

**Comment by trevorgerring** [comment]
For the MVP can we just have the user type in a date: MM/DD/YYYY? And then validate against that?

I would want to figure out and design a proper component for date pickers that we can use consistently going forward. I think we'd also give the user the option in the future to either type the date or select a calendar icon and input a date using that method.

**Comment by rakibansary** [comment]
Hi @trevorgerring - it'll be easier to change the date picker to one that lets you switch year, vs removing the current date picker and adding input mask to validate the user entered date. Should we just switch to a calendar UI for now while the date picker component design is in progress?

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/51

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh @trevorgerring , is this date picker fine for the MVP ?
<img width="1440" alt="Screenshot 2021-11-04 at 1 43 14 PM" src="https://user-images.githubusercontent.com/58783823/140279611-4bd3a398-45ab-491e-b813-00e0ff4b8224.png">

**Comment by trevorgerring** [comment]
@SathyaJayabal Yes, for MVP

OR we just remove it and just have the user type in a date AND change the "Select start date" placeholder to "MM/DD/YYY"

I don't have a preference, but feel that entering just a date might be easier than the current date picker being used

**Comment by SathyaJayabal** [comment]
Thanks.
