### ISSUE TITLE
Photo Editor - Can't Move Editing Circle

### ISSUE THREAD

**Issue by ClintonBon24** [topcoder-platform/micro-frontends-onboarding-app#38]
When you go to upload an image, it is pre-determining the circle. Most editors you can pinch/zoom, and shift the area you want to focus on. 
<img width="714" alt="Screen Shot 2021-11-03 at 8 25 07 PM" src="https://user-images.githubusercontent.com/93688953/140237085-93b18474-4f2f-429b-92a4-ec7f98fd0d20.png">

**Comment by rakibansary** [comment]
We currently do not crop the picture, so allowing pincing/zooming wouldn't serve any functionality. For now, we'll remove the pre-determined circle and show the entire picture in the preview.

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/49

**Comment by SathyaJayabal** [comment]
@rakibansary , we do crop the picture right?

**Comment by SathyaJayabal** [comment]
@rakibansary , got it, as we dont clip the photo in the back end.

**Comment by SathyaJayabal** [comment]
verified on dev, pre-determined circle is removed.
<img width="1440" alt="Screenshot 2021-11-04 at 2 17 00 PM" src="https://user-images.githubusercontent.com/58783823/140284183-d357c7e4-43b6-46b8-a672-f1101f90487e.png">
