### ISSUE TITLE
Next Screen does not start at top of screen

### ISSUE THREAD

**Issue by ClintonBon24** [topcoder-platform/micro-frontends-onboarding-app#39]
Finished screen #1 - moved onto Contact Details page, but the screen starts me here:

![image](https://user-images.githubusercontent.com/93688953/140237391-d8e3668a-47ab-4881-883b-315e36b3996c.png)

It should start me at the top of the screen.

**Comment by ClintonBon24** [comment]
Same on the following screen.

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/47

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/140298914-00808158-eb4f-410a-b611-2b32415d126c.mov
