### ISSUE TITLE
Should the Step Indicator be clickable 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#4]
Should the Step Indicator be clickable, so the user can jump to any completed step?

<img width="231" alt="Screenshot 2021-11-02 at 10 54 16 AM" src="https://user-images.githubusercontent.com/58783823/139791183-b06ffd33-2af2-47d5-9dd4-3205af11935a.png">

**Comment by LCDuggan** [comment]
Yes, functional to take the user to completed or in-progress steps.

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/140253569-432b396d-4654-4235-be02-0a0eeb10c7d0.mov
