### ISSUE TITLE
Letters Being "cut off" at bottom

### ISSUE THREAD

**Issue by ClintonBon24** [topcoder-platform/micro-frontends-onboarding-app#40]
In the text forms letters like "p" "q" anything with a "tail" is getting cut off visually.

![image](https://user-images.githubusercontent.com/93688953/140237709-dd73672f-b257-4b9f-ad4b-8c8a9986d642.png)

**Comment by SathyaJayabal** [comment]
We have it logged in https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/21
