### ISSUE TITLE
Incorrect Copy

### ISSUE THREAD

**Issue by ClintonBon24** [topcoder-platform/micro-frontends-onboarding-app#42]
I realize this copy was changed because right now we don't have the payment / tax part in the flow. 

If we don't get the payment part done before launch, this copy will need to be edited. 

![Uploading image.png…]()

**Comment by SathyaJayabal** [comment]
@ClintonBon24 , can you upload the image again please?

**Comment by SathyaJayabal** [comment]
the copy is updated now to remove the payment related text as we have added the payment step
<img width="1440" alt="Screenshot 2021-11-12 at 11 15 06 AM" src="https://user-images.githubusercontent.com/58783823/141416380-4fbb0b74-f165-4937-be5a-4a20f1395349.png">
