### ISSUE TITLE
Shouldn't this take me to my profile

### ISSUE THREAD

**Issue by ClintonBon24** [topcoder-platform/micro-frontends-onboarding-app#43]
If I click my uploaded image here (see image) shouldn't I go to my Topcoder profile? Right now, you only see a log out. 

![image](https://user-images.githubusercontent.com/93688953/140238438-3faf87ca-2545-4d0b-9bcb-0fa379530429.png)

**Comment by rakibansary** [comment]
When inside the /onboard flow, actions that take the user away from the onboard page are disabled/hidden. Specifically, three items are hidden

1) Switch tools
2) Notifications Icon
3) Profile menu item in the dropdown

![image](https://user-images.githubusercontent.com/1445965/140251748-4684fc0f-a3bf-4ead-bd54-af6d2c5b691f.png)

**Comment by SathyaJayabal** [comment]
@ClintonBon24 , we removed the link to the my profile so that the user cannot navigate away from the onboarding flow
