### ISSUE TITLE
New User Activation not redirecting to Onboard App

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/micro-frontends-onboarding-app#45]
cc @SathyaJayabal 

https://user-images.githubusercontent.com/51733042/140258318-0884bcd2-6181-491d-baaf-10bf18fe1905.mov

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/140474817-3c3a9626-162d-40a8-b857-97d9524bd36c.mov

**Comment by SathyaJayabal** [comment]
The activation email that is sent on first try has the incorrect return url

Actual: https://api.topcoder-dev.com/pub/activation.html?code=2FEXGEI6C5U&retUrl=https://accounts-auth0.topcoder-dev.com?retUrl=https://platform.topcoder-dev.com/
Expected: https://api.topcoder-dev.com/pub/activation.html?code=2FEXGEI6C5U&retUrl=https://accounts-auth0.topcoder-dev.com?retUrl=https://platform.topcoder-dev.com/onboard

**Comment by rakibansary** [comment]
This requires two updates before release

1. Marketing Website update to edit the retUrl - this has been tested and reverted back.
2. Update code that handles "Resend Email" trigger. This is currently deployed on DEV

Both these updates will be deployed once the decision is made to release the onboarding app.

**Comment by lakshmiathreya** [comment]
Onboard redirection is working fine for Signup on 1. Marketing site 2. CA Nav bar - verified on MacOS/Win/iOS/Android/Safari/Chrome/Edge/Firefox ...

Please note that we need to explore all other Signup routes and plan on fixing Onboard redirection for them next ...
