### ISSUE TITLE
Do not redirect to /onboard flow

### ISSUE THREAD

**Issue by rakibansary** [topcoder-platform/micro-frontends-onboarding-app#46]
We added a feature to redirect users who haven't completed the onboarding process to /onboard flow in [this commit](https://github.com/topcoder-platform/micro-frontends-navbar-app/pull/41). However we want to start the onboarding process only through the activation email. 

To that end, NavBar app should no longer redirect users to /onboard route.

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-navbar-app/pull/44

**Comment by SathyaJayabal** [comment]
@nursoltan-s , please use label `ready for review` when PR is ready instead of `Ready for QA`

**Comment by nursoltan-s** [comment]
@SathyaJayabal got it.

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/140298576-e8affd72-f188-47d0-ba53-9e14dd4f5e33.mov
