### ISSUE TITLE
V5 Member skills and member traits API must be used to get member data instead of v3

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#5]
V5 Member skills must be used to get member skills instead of V3
<img width="1440" alt="Screenshot 2021-11-02 at 11 14 46 AM" src="https://user-images.githubusercontent.com/58783823/139792837-9222ec76-1365-4cbe-a6d9-7a4944968ced.png">

<img width="1440" alt="Screenshot 2021-11-02 at 11 18 21 AM" src="https://user-images.githubusercontent.com/58783823/139793122-d7fe2e84-7ec8-47ed-a0b0-dc1ef3ac4de6.png">

**Comment by SathyaJayabal** [comment]
Patching member skills also must use V5 instead of V3
<img width="1440" alt="Screenshot 2021-11-02 at 11 20 53 AM" src="https://user-images.githubusercontent.com/58783823/139793444-702c4c17-b2ee-48e4-b5d5-84c3f9b42e7a.png">

**Comment by rakibansary** [comment]
Traits are now exclusively saved using v5 member Api. Skills however will need to continue to use v3 to save the skills. This is because for a newly registered user attempting to add skills using v5 fails. The user needs to have at least one skill attached to their profile for editing skills using v5 member Api.

**Comment by SathyaJayabal** [comment]
verified on dev:
1. V5 Member skills are used to get member skills
2. V5 member traits are used to get traits
3. V3 member skills are used to save member skills  as per https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/5#issuecomment-958973921
<img width="1440" alt="Screenshot 2021-11-03 at 7 12 41 PM" src="https://user-images.githubusercontent.com/58783823/140071463-43334d88-19e5-4963-9ecb-a374c6848bdd.png">
<img width="1440" alt="Screenshot 2021-11-03 at 7 13 11 PM" src="https://user-images.githubusercontent.com/58783823/140071504-af05df37-ea1e-4c8c-9105-dab3fc77f7c5.png">
<img width="1440" alt="Screenshot 2021-11-03 at 7 13 56 PM" src="https://user-images.githubusercontent.com/58783823/140071515-f39eefb0-d617-4023-9ecb-32ccda6d2556.png">
