### ISSUE TITLE
Fix typo on Get Started Page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#50]
Fix typo on Get Started Page
`ro` must be `to`

**Comment by rakibansary** [comment]
Corrected here: https://github.com/topcoder-platform/micro-frontends-onboarding-app/commit/8d78e46ee9d97dd073c674d74732fd73f5a6a6d8

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-11-04 at 12 11 39 PM" src="https://user-images.githubusercontent.com/58783823/140269166-682f412d-1ad9-4f7e-a161-881f68570e99.png">
