### ISSUE TITLE
Not able to remove the last selected user skill

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#54]
Not able to remove the last selected user skill

https://user-images.githubusercontent.com/58783823/140302405-2bde89dd-ade4-4bcf-b916-498dcae1d49f.mov

**Comment by dashu-baba** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/56

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. Able to remove the last selected user skill now.


https://user-images.githubusercontent.com/55895538/140468171-d188b63b-0c13-461b-9476-c764bb0ef056.mp4
