### ISSUE TITLE
UI - Images break when viewport is set to 1280px

### ISSUE THREAD

**Issue by LCDuggan** [topcoder-platform/micro-frontends-onboarding-app#55]
![Screen Shot 2021-11-03 at 11 50 17 AM](https://user-images.githubusercontent.com/93623041/140303207-ef1f1bfa-397b-48ff-ab57-43446e900f10.png)
![Screen Shot 2021-11-03 at 11 54 34 AM](https://user-images.githubusercontent.com/93623041/140303278-6a3a7d6b-a080-4457-83e8-fd619ccbb89e.png)

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/70

**Comment by SathyaJayabal** [comment]
@rakibansary , some of the text is cut off at the top and bottom

<img width="1217" alt="Screenshot 2021-11-08 at 9 17 59 AM" src="https://user-images.githubusercontent.com/58783823/140681546-b3dd7fd4-73d3-4bf0-b92b-7e56659ddb7a.png">

**Comment by nursoltan-s** [comment]
PR: https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/75
@SathyaJayabal

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1282" alt="Screenshot 2021-11-08 at 12 38 53 PM" src="https://user-images.githubusercontent.com/58783823/140698812-3341cda3-f87a-4f56-a3fa-f2578592d1d8.png">
<img width="1280" alt="Screenshot 2021-11-08 at 12 39 01 PM" src="https://user-images.githubusercontent.com/58783823/140698828-d605a676-7cc0-4069-ad5e-dded0f824753.png">
