### ISSUE TITLE
Select Design / UX Skills label is shown for other Skill tracks also.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#59]
Description:

Select Design / UX Skills label is shown for other Skill tracks also.

Steps to Reproduce:

1. Click Developer/Data science Skills under the Add your Skills field.
2. Observe the label displayed above the textfield displayed.
3. Try clicking the other tracks in the modal.
4. Again Observe the label.

Expected Result:
The related label should be displayed.

https://user-images.githubusercontent.com/55895538/140472174-394eca5e-5c68-443a-a72d-f9c49bd4e3aa.mp4

**Comment by dashu-baba** [comment]
Fix given at https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/61

**Comment by SathyaJayabal** [comment]
@rakibansary 
the label is missing the word skills
<img width="1440" alt="Screenshot 2021-11-05 at 3 38 20 PM" src="https://user-images.githubusercontent.com/58783823/140494297-ea27663a-a705-4396-b4a2-9b8414836f2f.png">
Design ref
<img width="932" alt="Screenshot 2021-11-05 at 3 39 21 PM" src="https://user-images.githubusercontent.com/58783823/140494364-0f6707ab-d796-4e80-ad54-4dea6e583850.png">

**Comment by dashu-baba** [comment]
fixed at https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/69

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-11-08 at 9 11 03 AM" src="https://user-images.githubusercontent.com/58783823/140680852-15879153-c315-44c7-bdfa-85ff271e3680.png">
<img width="1440" alt="Screenshot 2021-11-08 at 9 11 06 AM" src="https://user-images.githubusercontent.com/58783823/140680865-0dadbd26-9911-45d1-97c5-796466d69af1.png">
<img width="1440" alt="Screenshot 2021-11-08 at 9 11 08 AM" src="https://user-images.githubusercontent.com/58783823/140680869-f4dd9b6a-6596-4fa4-b2a9-2f1158a13d1f.png">
