### ISSUE TITLE
Inconsistent behaviour of Save

### ISSUE THREAD

**Issue by rakibansary** [topcoder-platform/micro-frontends-onboarding-app#62]
On getting started page

1. Upload -> Save immediately saves the users photo
2. Add Skills -> Save doesn't immediately save the added skills but are actually saved when user clicks "Continue"

Either both should immediately persist data in database or neither should.

**Comment by rakibansary** [comment]
Let's save Skills when user clicks "Save" button the Skills Modal.

**Comment by dashu-baba** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/72

**Comment by SathyaJayabal** [comment]
@rakibansary , with the same logic deleting the skills should also happen as soon as the user removes the skill right?
What do you think?
<img width="1440" alt="Screenshot 2021-11-08 at 12 43 20 PM" src="https://user-images.githubusercontent.com/58783823/140699283-e4991e15-1105-4327-ac79-f7e7791b90c4.png">

**Comment by rakibansary** [comment]
Inside the modal we have a "Save" action which I think should persist data in database. However when not in the modal, if we save when user removes Skills we end up with

1. User removes primary interests, these aren't saved unless user clicks "Continue to Contact Details",
2. User removes skills and these are immediately saved

So I think to be consistent, let,

1. "Save" action in the modal persist data
2. "Continue to Contact Details" save data when edits are done outside a modal

**Comment by SathyaJayabal** [comment]
thanks @rakibansary
