### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#63]
Description:

1. All the dropdowns in Onboarding screens are missing the dropdown arrow

![image](https://user-images.githubusercontent.com/55895538/140484789-5e6cace5-7b05-4630-8a73-f18fd825d99c.png)
![image](https://user-images.githubusercontent.com/55895538/140485046-b21e08ec-c32e-4aee-aa93-8443dc68ac3d.png)
![image](https://user-images.githubusercontent.com/55895538/140485253-f50b6f07-6418-403c-b0a0-381fba2b2031.png)

2. Date related fields are missing the calendar icon.

![image](https://user-images.githubusercontent.com/55895538/140485401-eb2bd2ab-25e2-4cf9-89e4-22e888e45c73.png)

**Comment by dashu-baba** [comment]
Fix given at https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/68

**Comment by SathyaJayabal** [comment]
@rakibansary 
`Date related fields are missing the calendar icon.` not fixed

<img width="1440" alt="Screenshot 2021-11-08 at 9 29 56 AM" src="https://user-images.githubusercontent.com/58783823/140682385-6205fbc7-6c0e-4f63-a15a-a0fd6b0319aa.png">

**Comment by dashu-baba** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/78

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-11-08 at 4 55 06 PM" src="https://user-images.githubusercontent.com/58783823/140734959-1aa5deb9-565e-4710-b0b0-b667ee547c08.png">

**Comment by SathyaJayabal** [comment]
@rakibansary , on clicking the date on the calendar, calendar is not closing

https://user-images.githubusercontent.com/58783823/140739976-e6fe82b6-ff83-4441-9ebc-44d8dc4ebc5a.mov

**Comment by SathyaJayabal** [comment]
Also the "Delete this job" and "Add another job" links extending even beyond the texts

https://user-images.githubusercontent.com/58783823/140740396-d8ba72a9-aca8-4b4e-91df-3f60cc110d0c.mov

**Comment by SathyaJayabal** [comment]
All the input fields must have a consistent font size
<img width="1005" alt="Screenshot 2021-11-08 at 5 48 40 PM" src="https://user-images.githubusercontent.com/58783823/140740981-dc5aea79-ff96-4e00-919f-81fb80132cf3.png">
Note: drop down and calendar fields have bigger fonts across steps 2 and 3.

**Comment by dashu-baba** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/80

**Comment by SathyaJayabal** [comment]
verified on dev
