### ISSUE TITLE
Dates entered in Onboarding are getting saved one day early in Profile settings page.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#64]
Description:

Dates entered in Onboarding are getting saved one day early in Profile settings page. Seems like a time zone problem.

![image](https://user-images.githubusercontent.com/55895538/140489421-6353050c-31e3-43dd-b9c3-8faf887114c2.png)

![image](https://user-images.githubusercontent.com/55895538/140489556-b1712d78-d4ff-43d6-b27a-6394e82a637b.png)

**Comment by dashu-baba** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/80

**Comment by SathyaJayabal** [comment]
@rakibansary , not yet fixed
<img width="1440" alt="Screenshot 2021-11-08 at 7 21 55 PM" src="https://user-images.githubusercontent.com/58783823/140753804-d91e21d0-d903-48a6-9fb4-a33b3abe09bf.png">
<img width="1440" alt="Screenshot 2021-11-08 at 7 22 00 PM" src="https://user-images.githubusercontent.com/58783823/140753825-9b80264e-9d55-4b3d-953e-4c4bf3cfea9c.png">

**Comment by sandhiyakavi** [comment]
@rakibansary Issue verified 


https://user-images.githubusercontent.com/55895538/140911269-a84fdf18-bd14-4225-979d-b1ffc1c20746.mp4

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-11-12 at 11 23 16 AM" src="https://user-images.githubusercontent.com/58783823/141417246-c21922b8-d9aa-4e9b-bd76-02f3fd30c7d3.png">
<img width="1440" alt="Screenshot 2021-11-12 at 11 23 32 AM" src="https://user-images.githubusercontent.com/58783823/141417261-d2f26aa8-bbdc-49a4-a0eb-ecbe5458e8e6.png">
