### ISSUE TITLE
Typo in Onboarding Complete page

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#66]
Description:

'learn' is missing in the paragraph displayed.

![image](https://user-images.githubusercontent.com/55895538/140493661-20d22b9c-ea60-4843-b9c2-c777734292f0.png)

![image (10)](https://user-images.githubusercontent.com/55895538/140493730-b2ac1cbc-4eb2-4323-ba67-bd9460f3b142.png)

**Comment by dashu-baba** [comment]
fixed at https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/69

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-11-08 at 9 13 38 AM" src="https://user-images.githubusercontent.com/58783823/140681107-eaa71ea9-4177-46ce-9b5f-547f826ea944.png">
