### ISSUE TITLE
Should "Home" be disabled inside the Onboarding flow

### ISSUE THREAD

**Issue by rakibansary** [topcoder-platform/micro-frontends-onboarding-app#82]
When in the onboarding flow we hide

1. Tool Switcher
2. Notifications Icon
3. Profile link in the dropdown

![image](https://user-images.githubusercontent.com/1445965/140871956-7c5a3517-dd0c-4e44-896a-831f4a3a77f0.png)

Clicking the Top Left icon on the navbar will still navigate the user to https://platform.topcoder.com. Should this be disabled inside the onboarding flow?

**Comment by Oanh-and-only-Oanh** [comment]
Yes, let's disable Home on top left navbar.

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-navbar-app/pull/48

**Comment by sandhiyakavi** [comment]
@rakibansary Now the nav bar itself is completely hided. The user won't be able to even logout of the application. Is it expected?

Also the Firstname,Lastname are not correctly displayed now
![image](https://user-images.githubusercontent.com/55895538/141048137-ee3af64d-b606-4ad6-9220-1d5c0579445f.png)

**Comment by rakibansary** [comment]
The NavBar should be visible. I'm not seeing the reported behaviour though

![image](https://user-images.githubusercontent.com/1445965/141049220-3b382576-9e04-4352-8fe5-4fcccb8e4243.png)

**Comment by sandhiyakavi** [comment]
@rakibansary If the onboarding procedure has already reached step 4 (complete) ,the nav bar is visible.

**Comment by rakibansary** [comment]
@sandhiyakavi this was an issue with navbar not rendering for users who has first name and/or last name undefined. https://github.com/topcoder-platform/micro-frontends-navbar-app/pull/51 should fix this issue.

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Working as expected.
