### ISSUE TITLE
Some skills in the Skills dropdown are duplicated

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#85]
Description:

Some skills in the Skills dropdown are duplicated

https://user-images.githubusercontent.com/55895538/140887068-bf552c1b-2018-4488-8e08-f0504284da06.mp4

**Comment by rakibansary** [comment]
Skills Api has duplicate skills (same label). However they have different taxonomyName. For example

```json
  {
    "id": "60b46fd4-3bb6-4b58-ac2b-d36647767e7a",
    "name": "Java",
    "externalId": null,
    "uri": null,
    "metadata": {
      "updated": "2020-11-02T19:47:05.717Z"
    },
    "taxonomyId": "e8467a61-7e20-4ed2-a839-c6340d90f408",
    "taxonomyName": "Topcoder"
  },
```

and 

```json
  {
    "id": "581afd4b-8958-4538-af6e-a1f272a179df",
    "name": "Java",
    "externalId": null,
    "uri": null,
    "metadata": {
      "updated": "2020-11-02T19:47:08.740Z"
    },
    "taxonomyId": "37f6fb04-b53c-4039-815e-b0ac158324e1",
    "taxonomyName": "Wipro Digital"
  }
```
One solution here might be to only list skills where taxonomyName == 'Topcoder' when there's duplicates.

**Comment by sandhiyakavi** [comment]
Verified in Prod Env.

The skills are not duplicated now.

![image](https://user-images.githubusercontent.com/55895538/141048687-8ce31f3b-870b-41ce-9970-40b6f8f50b38.png)
