### ISSUE TITLE
The Skills added under the Development track are not getting removed.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#86]
Description:

The Skills added under the Development track are not getting removed. 

https://user-images.githubusercontent.com/55895538/140887368-23152176-3ff2-404a-bc18-f597bfb3bc3f.mp4

https://user-images.githubusercontent.com/55895538/140889128-3241e50b-92d5-4e58-9d71-4f167b5efc40.mp4

**Comment by rakibansary** [comment]
@dashu-baba can you please take a look at this one? This is reproducible in DEV environment.

**Comment by sandhiyakavi** [comment]
Verified in both Dev and Prod Env.


https://user-images.githubusercontent.com/55895538/141049574-a913b872-8566-41d2-b976-6b076ea1ffdc.mp4


https://user-images.githubusercontent.com/55895538/141049585-ab721fff-b55c-4f2e-9103-7e850e50bff3.mp4
