### ISSUE TITLE
Page is getting loaded continuously while trying to save the Contact details 

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#87]
Description:

Page is getting loaded continuously while trying to save the Contact details. Getting error message "The trait id connect_info already exists for the member" for POST/v5/members/testsaarob1/traits.

Note: Only Address line 1 and 2 are able to be saved successfully.

![image](https://user-images.githubusercontent.com/55895538/140890978-56312489-32a2-4ea5-9b50-080a0ce58e10.png)

https://user-images.githubusercontent.com/55895538/140891087-dd8ed8d0-bb57-46fa-935a-d8baf9d59699.mp4

**Comment by sandhiyakavi** [comment]
This issue exists for the Language skills as well

![image](https://user-images.githubusercontent.com/55895538/140893583-601f4ab3-e86c-4b7c-ac73-fc239ac6417f.png)

**Comment by drasticdpk** [comment]
Verified on Dev mode.
![image](https://user-images.githubusercontent.com/25297859/141136515-2234361d-b7c9-4e02-a9d0-edfc4e07b82d.png)


Note : I can make  complete profile step by step. cc @sandhiyakavi

**Comment by lakshmiathreya** [comment]
Transition to each next step in working fine ... Address Line 1, Line 2, Title and Bio not being saved ... will log that in a new Issue..
