### ISSUE TITLE
Not able to update the Title and Bio entered

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#88]
Description:

Not able to update the Title and Bio entered

https://user-images.githubusercontent.com/55895538/140893904-8057a3bb-f627-4ef3-ab0c-163ddff0d691.mp4

**Comment by sandhiyakavi** [comment]
@rakibansary similarly, I am not able to remove the added ones in the Select your interest at Topcoder field also

![image](https://user-images.githubusercontent.com/55895538/140900604-567eb04d-7bda-4a3e-92f2-f24e4a7a5577.png)

**Comment by SathyaJayabal** [comment]
Tested on prod. 
User is able to remove primary interests, 

https://user-images.githubusercontent.com/58783823/141419789-3a9bbbbd-3d1f-440b-8559-49d3f88f75b3.mov


But sometimes the user is not able to see the updated title and bio. 

https://user-images.githubusercontent.com/58783823/141420078-89462916-8ae6-4df3-ba7e-627bcb556279.mov

**Comment by SathyaJayabal** [comment]
issue with primary interest is logged here:
https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/148

**Comment by SathyaJayabal** [comment]
This seems to be an issue with the DB and ES sync (issue logged here https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/147). Checked that the actual updated values are present in the DB.
