### ISSUE TITLE
Contact Details: Working hours format

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#9]
The working hours format used here is different from the one used on the connect profile.
ref: https://github.com/topcoder-platform/micro-frontends-onboarding-app/blob/develop/src/constants/workinghours.json
https://connect.topcoder-dev.com/settings/profile

Hence if we select values like (09:00 , which is 9:00 in connect, or 10:30 , which is not present in connect), these values will not be reflected on the connect profile. 

We should have the same format in both places so that changing in one place will reflect correctly in the other place.

<img width="1440" alt="Screenshot 2021-11-02 at 1 17 53 PM" src="https://user-images.githubusercontent.com/58783823/139806537-b93c4461-f24a-4469-832a-90d6ec475b95.png">
<img width="1440" alt="Screenshot 2021-11-02 at 1 20 14 PM" src="https://user-images.githubusercontent.com/58783823/139806563-38936dc1-ecc8-4558-95d3-261852ca8937.png">

**Comment by vikasrohit** [comment]
I agree. @rakibansary you can reuse the component from https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/Formsy/WorkingHoursSelection.jsx or if that creates trouble (I expect it to conflict with react version we are using in MFE), you can copy the list from there for the time being.

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-11-03 at 8 38 54 PM" src="https://user-images.githubusercontent.com/58783823/140087269-40cec759-4ffe-42e3-bae6-98ea7896e510.png">
