### ISSUE TITLE
Issues with the Start date and End date of the Education and Work Experience fields

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-onboarding-app#91]
Description:

1. The user is able to add Future dates to the End date of Work Experience field but not able to save the same. In community app, the Future dates are disabled.

https://user-images.githubusercontent.com/55895538/140911995-dee566a9-2ac4-4ef6-8690-18c3920bf06d.mp4

2. For Education field we need to allow entering future dates, but future dates are not getting saved in MFE.

https://user-images.githubusercontent.com/55895538/140912233-8220b0c1-7c1f-4096-ab21-56c59489448f.mp4

3. Able to enter the End date field eventhough the user clicked the "I am currently working in this role" checkbox.

![image](https://user-images.githubusercontent.com/55895538/140912856-fdb2d54d-18be-48ab-a50f-e306183a66c1.png)

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/103

**Comment by sandhiyakavi** [comment]
This issue can be completely tested only after the issue https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/87 is resolved

**Comment by drasticdpk** [comment]
Verified 1 & 3. 
For Point 3, User should be able to enter future date 
**Reference** 
![image](https://user-images.githubusercontent.com/25297859/141139854-71e8d3de-6765-4461-a49f-3308de4227dd.png)

**Comment by nursoltan-s** [comment]
[083398](https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/120)

**Comment by sandhiyakavi** [comment]
For verifying Point#2 , the issue #137 should be resolved

**Comment by sandhiyakavi** [comment]
Verified in Prod

![image](https://user-images.githubusercontent.com/55895538/141421347-c5fa365e-99dd-448a-a41e-e7daf409a87f.png)
