### ISSUE TITLE
User can upload image more than given size.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/micro-frontends-onboarding-app#96]
**Steps** 
- Try to upload photo more than 2MB

**Reference** 

![image](https://user-images.githubusercontent.com/25297859/140982180-df8f54c7-6219-4bc5-9abe-738ac133594c.png)

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/102

**Comment by drasticdpk** [comment]
@nursoltan-s Can we give some message to user when they upload more than 2MB file? 

**Reference**
![image](https://user-images.githubusercontent.com/25297859/141096189-26f6480f-3914-4d1d-bdb4-115ffcbaf1f8.png)

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/122

**Comment by trevorgerring** [comment]
I would add the message to the middle text area. See images
![Screen Shot 2021-11-10 at 10 09 43 AM](https://user-images.githubusercontent.com/21342409/141160022-9e1acd8c-6b3a-4bbb-adbe-a5739e2f00c3.png)

![Screen Shot 2021-11-10 at 10 09 24 AM](https://user-images.githubusercontent.com/21342409/141160041-ce9a2259-4ef2-4d4c-a46d-aee7bbe15c72.png)

Text CSS:
Weight - 500
Color - #EF476F;

**Comment by nursoltan-s** [comment]
<img width="1396" alt="Screen Shot 2021-11-11 at 09 57 37" src="https://user-images.githubusercontent.com/7783676/141223374-40071e44-1cbd-4545-9bfd-32fc4cd948e7.png">

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/125

**Comment by sandhiyakavi** [comment]
verified in Prod Env.

![image](https://user-images.githubusercontent.com/55895538/141256370-655014ad-4e8a-4c64-a7df-2d6a50cca213.png)
