### ISSUE TITLE
SELECT YOUR INTERESTS AT TOPCODER field is missing 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/micro-frontends-onboarding-app#97]
**Steps**
- Add Any filed on SELECT YOUR INTERESTS AT TOPCODER
- Click on Continue Button 
- Click Back Button and observe the selected item.

**Reference** 

https://user-images.githubusercontent.com/25297859/140988902-90b3d1bf-8254-445c-9ab2-506576065d76.mp4

**Comment by drasticdpk** [comment]
Developer Note : Getting this error while updating the above information at second time. 
![image](https://user-images.githubusercontent.com/25297859/140989815-5058295c-4100-436b-a7a5-0a28e52a0ae8.png)

**Comment by rakibansary** [comment]
Hi @drasticdpk,

Can you please confirm if the user you logged in as was a new user or an existing user?

Thanks

**Comment by drasticdpk** [comment]
Hi @rakibansary , 
Yes this is new user, I have created this acc today only.
![image](https://user-images.githubusercontent.com/25297859/140995445-6e430976-7b8d-4ce5-a83b-be799ce84609.png)

**Comment by drasticdpk** [comment]
@rakibansary 
Finding
Still we are having same issue. 
FYI I have tried with new user. Please try to replicate by clicking continue/back button 2 or 3 times. 
**Reference** 
https://user-images.githubusercontent.com/25297859/141133871-e5a8b171-486e-436f-a8a5-a637e8291286.mp4

**Comment by rakibansary** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/121/commits/48695d83f2bc260d6bbcef621a4dc9d73423f8ea should fix this issue.

**Comment by sandhiyakavi** [comment]
Verified the issue in Prod Env. The field is getting saved now.
