### ISSUE TITLE
Page not found message is missing.

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/micro-frontends-onboarding-app#99]
- Enter the invalid URL followed by given application  https://platform.topcoder.com/onboard/invalidurl

**Reference** 
![image](https://user-images.githubusercontent.com/25297859/140991847-24fc6021-ad49-441a-b3aa-91932e6aa30c.png)

**Expectation**

![image](https://user-images.githubusercontent.com/25297859/140992145-849cf337-2301-4c69-8353-c73f8a928b16.png)
https://platform.topcoder.com/onboardfdads

**Comment by rakibansary** [comment]
Hi @drasticdpk 

If you land on https://platform.topcoder.com/invalid-url you'll see an example of TC MFEs not having a generic "404 Page" handler. For now we are not handling bad links in the onboarding app.
